# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
# Upload management flag: a

title: "八王子市合気道連盟 みなみ野教室"
email: minamino@seishin-kan.com
description: >- # this means to ignore newlines until "baseurl:"
  八王子市合気道連盟が主催する入門者・初心者向け「市民のための合気道教室」です。
  ※最新稽古予定などはTwitterをご覧ください。
  An Aikido class for beginner, run by Hachioji-shi Aikido Association.
#baseurl: "/minamino-aikido" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AikidoMinamino
github_username:  minamino-aikido
#facebook_username: aikido.minamino
timezone: Asia/Tokyo
paginate: 6
tagline: 入門・初心者向け「市民のための合気道教室」
embed_tweets: yes
sidebar_list: ["google-calendar.html"]
google_calendar_url: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;mode=AGENDA&amp;height=240&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=minamino.aikido%40gmail.com&amp;color=%231B887A&amp;ctz=Asia%2FTokyo
adsense_client_id: ca-pub-9466084318094329
post_list_title: "お知らせ / コラム"
favicon: "/favicon.svg"

# Build settings
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: aikige/minamino-aikido
header_pages:
  - about.md
  - contacts.md
  - getting_started.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Dockerfile
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - test/
 - LICENSE
 - README.md
 - "*.bak"
 - "*.bat"
 - "*.sh"
